### ISSUE TITLE
JavaFX support

### ISSUE THREAD

**Issue by tobium** [konsoletyper/teavm#127]
It would be great to use JavaFX to create apps running via TeaVM on browser. So we need a JavaFX prism renderer for HTML5-Canvas via TeaVM...

**Comment by konsoletyper** [comment]
To run JavaFX apps upon TeaVM, you should first rewrite JavaFX upon TeaVM. It's quite fair amount of work! It's obviously not a part of TeaVM. You can create your own project, possibly, by forking JavaFX and porting it to TeaVM, if even possible, since it could require reflection, class loaders, access to Jar file resources, etc, which is beyond the scope of TeaVM.
