### ISSUE TITLE
OSGi Container Support

### ISSUE THREAD

**Issue by zzj1213** [konsoletyper/teavm#151]
Can compile an OSGI container ?

**Comment by konsoletyper** [comment]
Very doubtfully, since TeaVM does not support reflection and class loading

**Comment by zzj1213** [comment]
Thanks for the reply.  Any suggestion for a component framework under TeaVM ?

**Comment by konsoletyper** [comment]
What do you mean after "component framework"?

**Comment by zzj1213** [comment]
Something similar to OSGi container to develop web application by developing and assembling bundles.

**Comment by konsoletyper** [comment]
Why do you need OSGi to develop web applications? I can barely call OSGi "component framework". Yes, it helps you to write application in terms of components, but you still can write then without OSGi. What OSGi does is (a) can dynamically load/unload bundles (b) checks some API constraints during class loading and (c) solves JAR hell problem. TeaVM does not do any classloading, since it is an AOT compiler. A bundle is an ordinary jar file (with something additional in manifest file) which you can certainly use out of OSGi container.

What are you requirements to a "component framework"? If any of a, b and c points above, I can say that it is impossible in TeaVM. Maybe you need something similar to blueprint? No, TeaVM still has nothing similar, but it is possible to implement DI framework for TeaVM. In this situation I can recommend you so called poor man's DI.
