### ISSUE TITLE
GWT ClientBundle like resource deployment

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#156]
CientBundle like resource deployment is needed. Is there a deferred binding mechanism in teavm?

**Comment by konsoletyper** [comment]
For what purpose do you need ClientBundle? Can't you refer images, stylesheets, etc, by direct link?

There is no direct alternative to deferred binding, since GWT generators produce Java code, while TeaVM works with bytecode instead of source code. However, there are extension mechanisms which allow you to do similar things. Unfortunately, I don't have time to create documentation. Nor does GWT team, I had to learn generators from examples and a couple blog posts.

I can give you a point to start. Please, look at [TeaVMPlugin](https://github.com/konsoletyper/teavm/blob/master/core/src/main/java/org/teavm/vm/spi/TeaVMPlugin.java). You can implement it and put implementor class name to `META-INF/services/org.teavm.vm.spi.TeaVMPlugin` file. Major examples are [JSOPlugin](https://github.com/konsoletyper/teavm/blob/master/jso/impl/src/main/java/org/teavm/jso/impl/JSOPlugin.java) and [JSONPlugin](https://github.com/konsoletyper/teavm-flavour/blob/master/json/src/main/java/org/teavm/flavour/json/emit/JSONPlugin.java). Let me know if you need some assistance in writing you own plugin.

**Comment by bertung** [comment]
ClientBundle can embed images and text of certain size into the produced Javascript code. ıt converts images to data URI equivalents. Larger images are generated as direct links. Generating an implementated version of an interface is very useful for extensibility especially in an environment where reflection could not be supported. How would one use reflection if wanted to with teaVM?

**Comment by konsoletyper** [comment]
> ClientBundle can embed images and text of certain size into the produced Javascript code. ıt converts images to data URI equivalents. Larger images are generated as direct links

TeaVM is not GWT. TeaVM is a compiler, while GWT is compiler and web framework. Optimizing resources is not a job of compiler, right? Of course, you can create framework for TeaVM that helps to optimize resources, but are you sure there's no way except reinvening ClientBundle? AFAIK, it comes from mid 2000-s, and today we have plenty of tools to speed-up loading. Did you try to use SPDY instead of HTTP?

> Generating an implementated version of an interface is very useful for extensibility especially in an environment where reflection could not be supported. 

TeaVM supports metaprogramming, see links above. It does not allow you to generate source code, but you can still generate or alter its own intermediate representation (IR) which is very similar to Java bytecode.

> How would one use reflection if wanted to with teaVM

There's no way to incorporate reflection into TeaVM. One should use alternative approaches, depending on a specific task.

**Comment by bertung** [comment]
ClientBundle is an indirect answer to the Java's getResource. We do not use the web framework part of GWT, so it is just a compiler to us. Thank you for the quick responses. I will continue to follow TeaVM development.
