### ISSUE TITLE
Question: How can I get the real JS function instance of a Functor ?  

### ISSUE THREAD

**Issue by leobm** [konsoletyper/teavm#158]
hi Alexey,

with the following code:

https://gist.github.com/leobm/0e1ae4272fb0a5f1435f

Can you tell me how I can get the real Javascript function instance of the Functor ? The call to apply in the last line calls the apply method of the functor.
My Idea was to cast the functor to a real javascript function instance and then call the apply
function of this instance. I think I have to modify the static "of" method of my JSFunction class?

thanks,
Felix

**Comment by konsoletyper** [comment]
TeaVM relies on run-time wrapping of functors. TeaVM does not perform runtime checks, instead it checks declared parameter type. If parameter type is functor interface, it wraps your object into function. The problem is that `JSFunction.of` takes `JSFunctorBase`, which is not a functor interface, so TeaVM passes it as object. So you can't make your code work this way. Instead, you can write something like this:

```java
public final class FunctionConverter {
    @JSBody(params = "functor", script = "return functor;")
    public static native JSFunction wrap(JSFunctor2<?, ?, ?> functor);
}
FunctionConverter.wrap(func).apply(null, JSArray.of(JSNumber.valueOf(1), JSString.valueOf("Hello")));
```

**Comment by leobm** [comment]
ok, that makes sense. 
thanks...
