### ISSUE TITLE
what happens when a property of JSObject does not exist?

### ISSUE THREAD

**Issue by ambahk** [konsoletyper/teavm#161]
When the following code is added as a JUnit test, it will pass.  But when it is executed in a browser (tested Safari and Chrome), obj.getA() will fail because the property does not exist in that object.  On Safari the failure says *TypeError: undefined is not an object (evaluating 'str.length')*

May I know what's the intended behaviour?  Thanks.

```
public class Client {
    
    public interface TestObj extends JSObject {
        
        @JSProperty
        String getA();
        
        @JSProperty
        void setA(String a);
    }
    
    @JSBody(params = {}, script = "return {}")
    public static native TestObj newTestObj();

    public static void main(String[] args) {

        HTMLDocument document = HTMLDocument.current();
        
        TestObj obj = newTestObj();
        String x = obj.getA();

        HTMLElement div = document.createElement("div");
        div.appendChild(document.createTextNode(x));
        document.getBody().appendChild(div);
    }
}
```

```
@Test
void convertUndefinedProperty() {

        TestObj obj = newTestObj();

        assertEquals(null, obj.getA());
        obj.setA("b");
        assertEquals("b", obj.getA());
}
```

**Comment by konsoletyper** [comment]
> May I know what's the intended behaviour? Thanks.
> |public class Client { public interface TestObj extends JSObject { 
> @JSProperty String getA(); @JSProperty void setA(String a); } 
> @JSBody(params = {}, script = "return {}") public static native 
> TestObj newTestObj(); public static void main(String[] args) { 
> HTMLDocument document = HTMLDocument.current(); TestObj obj = 
> newTestObj(); String x = obj.getA(); HTMLElement div = 
> document.createElement("div"); 
> div.appendChild(document.createTextNode(x)); 
> document.getBody().appendChild(div); } } |
The indented behaviour is to get the error, since newTestObj returns 
empty object with no properties. When you access obj's property that 
does not exist, you get an error. You should set some value first or you 
can make your newTestObj like the following:

|@JSBody(params = {}, script = "return { a : null };") public static 
native TestObj newTestObj();|

Another option is to test whether a property exists:

@JSBody(params = "obj", script = "return 'a' in obj;")
public static native boolean isADefined(TestObj obj);

TestObj obj = newTestObj();
String x = isADefined(obj) ? obj.getA() : "undefined";

||

**Comment by konsoletyper** [comment]
The indented behaviour is to get the error, since newTestObj returns 
empty object with no properties. When you access obj's property that 
does not exist, you get an error. You should set some value first or you 
can make your newTestObj like the following:

```java
@JSBody(params = {}, script = "return { a : null };") public static 
native TestObj newTestObj();|
```

Another option is to test whether `a` property exists:

```java
@JSBody(params = "obj", script = "return 'a' in obj;")
public static native boolean isADefined(TestObj obj);

TestObj obj = newTestObj();
String x = isADefined(obj) ? obj.getA() : "undefined";
```
