### ISSUE TITLE
Missing wheel value in MouseEvent.

### ISSUE THREAD

**Issue by Wolftein** [konsoletyper/teavm#192]
Cannot get the value of the wheel when "wheel" event happen using EventListener<MouseEvent>.

**Comment by konsoletyper** [comment]
Right, because [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) knows nothing about wheel. There's missing wrapper for [WheelEvent](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent), which you can create yourself as a workaround. You probably need to read [JSO documentation](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript) for this purpose.

**Comment by Wolftein** [comment]
I may have expressed wrong, i created the wrapper myself as a workaround, thanks.
