### ISSUE TITLE
Compiled JS code

### ISSUE THREAD

**Issue by WhiteTrashLord** [konsoletyper/teavm#200]
I am currently searching for a good replacement for GWT. TeaVM looks very promising.
But the compiled JS code looks a bit strange to me.

Why there are functions like $rt_ustr or $rt_str used for Strings? To me it looks like this slows down the code.

And my JS code is full of something like this:

function MD(){E.call(this);}
function LB(){E.call(this);}
function YB(){E.call(this);}
function HC(){E.call(this);}
function UB(){E.call(this);}

The compiler performs some kind of obfuscation?
If yes, it's possible to change the compiled JS output to pretty style like it's possible in GWT?

**Comment by konsoletyper** [comment]
> Why there are functions like $rt_ustr or $rt_str used for Strings?

Because `java.lang.Object` is not a JavaScript `Object`, since JS knows nothing about `equals`, `hashCode` and monitors, and polluting `Object`'s prototype is a very bad idea. It's impossible to change prototype of `String`. Also, TeaVM was initially designed to be more than purely JS translator (and there is `llvm` branch with experimental LLVM compiler), so fair `java.lang.String` is easy to share between different backends 

> To me it looks like this slows down the code.

You should not suppose. You should measure.

> The compiler performs some kind of obfuscation?
> If yes, it's possible to change the compiled JS output to pretty style like it's possible in GWT?

Please, read the docs before asking. [Here](https://github.com/konsoletyper/teavm/wiki/Building-JavaScript-with-Maven-and-TeaVM), look at `minifying` flag.

**Comment by WhiteTrashLord** [comment]
Thank you and sorry. I should have really checked this wiki site.

I produce only very simple code. I noticed that the generated JS code is also full of code for classes like "java.io.Closeable" and "java.io.Flushable" which I will never use. Is there an approach how to reduce this kind of code?

**Comment by konsoletyper** [comment]
You will never use it directly, but you actually use it indirectly. You probably invoke something like `System.out.println`, right? Remember, `System.out` is a `PrintStream` which implements these interfaces. TeaVM is clever enought to remove everything you don't need to run a program. Discovering this manually is pretty annoying and time consuming.

**Comment by WhiteTrashLord** [comment]
No, I tested some super simple code:

    public static void main(String[] args) {        
    	Window.alert(Window.current());   	
    }

In my code no Java object is used. Does this extra code comes from the String [] args object?
