### ISSUE TITLE
Use without maven. 

### ISSUE THREAD

**Issue by ianopolous** [konsoletyper/teavm#221]
Is there a place to download a release that I can use without maven. I'd like to use it from the command line without maven, ideally in ant. 

I'm working on a security sensitive project and having maven randomly download stuff over http is not an option.

**Comment by ianopolous** [comment]
I've built teavm from source, do I need all the 12 or so (non test) jars?

**Comment by konsoletyper** [comment]
No, there's no official documented way of using TeaVM without Maven. There's 3rd party Gradle plugin somewhere. I believe, since its author could create the plugin without my help, it won't be hard for you to learn how to run TeaVM programmatically, which helps you create any tooling you need. You need most of the JARs, look through `pom.xml` files, everything must be clear. Take a look at `teavm-cli` module. I don't provide official documentation for it, you must learn how to use it yourself.

Maven won't download anything randomly. It downloads dependencies which are not installed in your local repository. You can specify remote repository location. Also, Maven has very good property that once uploaded artifacts can't be changed (only new versions can be uploaded), and all artifacts are signed. You can use HTTPS/SSL if you want more security. IMO, it's more safe to use Maven that downloading dependencies manually, which often is a major security risk.

**Comment by ianopolous** [comment]
Sure, it's not random, but using the maven defaults from a fresh git clone downloaded everything over http, which means anything can trivially be changed by a MITM. 
Personally I prefer to check in all my dependencies which makes auditability and reproducible builds possible,and removes a failure mode when the external server is unavailable/shuts down.
