### ISSUE TITLE
WASM: Unreferenced but exported methods are removed by dependency checker

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#258]
Consider the following code:

```
package de.mirkosertic;

import org.teavm.interop.Export;

public class Main {

    @Export(name = "passThru")
    public static int passThru(int aValue) {
       return aValue + 1;
    }

    public static void main(String[] args) {
    }
}
```

The passThru Method is removed by dependency checker, probably as it seems to be unused from the Java bytecode point of view. But the methods is intended to be called from JavaScript. 

Exported methods should always be part of the dependency graph.

**Comment by konsoletyper** [comment]
It's an issue by design. TeaVM does not scan full classpath, since it can be large and imply big compilation time. It rather starts from known *main* class and then parses additonal classes when they are reached by dependencies. There must be a way to tell TeaVM that a certain method should be scanned. `@Export` annotation can't serve for this purpose, it's only purpose is to tell TeaVM to generate certain WebAssembly instructions.

**Comment by mirkosertic** [comment]
I created pull request #259 as a proposal.

You are right, we cannot search the whole classpath for annotated methods. But we can search the already processed classes and for @Export annotated methods and mark them as used during dependency analysis. This mechanism would make the example code from above workable.

This is definitely a tradeoff between performance and usability, but it is better than nothing.
