### ISSUE TITLE
Reflection support

### ISSUE THREAD

**Issue by sriharshachilakapati** [konsoletyper/teavm#294]
I was browsing through the sources of TeaVM as I'm currently evaluating whether I can safely migrate my existing code base (~2000 classes and interfaces) from GWT to it, and a commit caught my attention.

12dded7 - JS: add reflection support for methods

This is interesting, I browsed through the wiki and the main site teavm.org but can't find any other information on this. Is this possible? If it is, then how should I be using it?

My use case is that I'm a game developer, and I currently have a mechanism that allows me to use tools to create entities. These entities will contain the class names of the components attached to them, and are written to text files, and at runtime I instantiate the components based on the name.

~~~java
Class<? extends Component> cls = Class.forName(componentClassName);
// ... instantiate it to get a Component object and add it to the entity
~~~

Is this kind possible in TeaVM? In GWT, I'm currently using Generators to write a new class that returns the object at compile time that enumerates all the component class names in the compile path.

If the only issue for reflection is the size, then it may be a good idea to allow for a property that selects the classes that should be kept at all cost?

**Comment by konsoletyper** [comment]
There will be method and field reflection support in TeaVM 0.6.0, however it's still far from being released, so I haven't provided any documentation yet. If you want to use reflection, you may build TeaVM yourself and use version from your local Maven repository.

As for current versions, reflection *is* available, but it's very limited. You can't access fields and methods of classes. These commits you mention don't introduce "full reflection support", they just add some features which weren't available before.

You can use `Class.forName` and `Class.newInstance()` from 0.5.x, with only one limitation: you have to mention classes available from `Class.forName` somewhere in the reachable methods (`main` method is a good candidate). This may be, for example, a class literal you pass to some function. Example is:

```
static void main(String[] args) {
    someMethod9(A.class, B.class);
}

static void someMethod(Class<?>... classes) {
    for (Class<?> c : classes) {
        System.out.println(c.getSimpleName());
    }
}
```

The reason is: to produce small JS files, TeaVM will only compile classes/methods it can observe, and won't compile any other classes.

To use method and field reflection with recent commits, you should notice one thing. Although TeaVM will properly provide metadata for methods and fields, it will prohibit `Field.get`,`Field.set` and `Method.invoke` by default for all fields and methods. You can ask TeaVM to enable access to particular fields and methods. You should implement `ReflectionSupplier` interface and register your implementation via `ServiceLoader` convention, i.e. by adding following resouce file: `META-INF/services/org.teavm.classlib.ReflectionSupplier` with only one line containing fully-qualified name of your implementation. There's example implementation you can find somewhere in TeaVM codebase named `ReflectionSupplierImpl`.

I don't recommend you using reflection in TeaVM, because, in general, reflection is an optimization killer. The recommended approach is to use [metaprogramming](https://github.com/konsoletyper/teavm/wiki/Metaprogramming) capabilities of TeaVM, which are quite similar to GWT generators. However, metaprogramming API is not a solution in your case, since it can't access full list of compiled classes (since there's no such thing at all in TeaVM internally, and won't be ever). Another solution is to throw away both reflection and generators and use something like this:

```java
private stataic Map<Class<?>, Supplier<Object>> componentSuppliers = new HashMap<>();

static {
    componentSuppliers.put(A.class, A::new);
    componentSuppliers.put(B.class, B::new);
    // etc
}
```

**Comment by norzak** [comment]
Any plans to support Dynamic Proxies?

**Comment by konsoletyper** [comment]
@norzak no plans. For what puprpose do you need them. Did you try metaprogramming API, which supports proxies?

**Comment by norzak** [comment]
I know metaprogramming API has proxies. I was just curious if you had any plans to support the standard Java dynamic proxies.

**Comment by konsoletyper** [comment]
I do not do things out of curiosity. If you have any important use case, if you are going to port existing project to TeaVM and lack of `Proxy` class is the only show stopper, I'll be glad to include it into roadmap.

**Comment by WolfieWerewolf** [comment]
Hi Alexey,  me again.. I hope all is well my friend.  I've been playing around with reflection again; I'm testing Method reflection.  Using your ReflectionSupplierImpl example I had one issue that I wanted to report.  For getAccessibleMethods it's iterating all classes loaded by the project, including those provided by the JDK and, at least in my test, it bails.  I added a simple filter for only the package that I was interested in, the package that uses the @Reflectable annotation and that resolved it.  I would be happy to submit a PR but I wondered how you would want to handle this?  Here's a sample of my changes.

```java
@Override
    public Collection<MethodDescriptor> getAccessibleMethods(ReflectionContext context, String className) {
        Set<MethodDescriptor> methods = new HashSet<>();
        if(className.contains("software.wolfpack")){
            ClassReader cls = context.getClassSource().get(className);
            cls.getMethods().forEach(method->{
                if (method.getAnnotations().get(Reflectable.class.getName()) != null) {
                    System.out.println(method.getDescriptor());
                    methods.add(method.getDescriptor());
                }
            });
        }
        return methods;
    }
```
Thanks again for including Reflection in the mainstream I very much appreciate you doing this.

Kind Regards

/W
