### ISSUE TITLE
ArrayList implementation differs from HotSpot one

### ISSUE THREAD

**Issue by jtulach** [konsoletyper/teavm#310]
I run into issues with [Charts API](https://dukescript.com/javadoc/charts/) code. It runs on HotSpot, Bck2Brwsr, but it doesn't run on TeaVM. This code is the core of the problem:
```java
            class SpecialArrayList extends ArrayList {

                @Override
                public void add(int at, Object o) {
                    throw new UnsupportedOperationException();
                }
            }
            SpecialArrayList arr = new SpecialArrayList();
            arr.add(this);

            results.add(arr.size());
```
with TeaVM (tested on 0.5.1) it throws `UnsupportedOperationException`.

**Comment by konsoletyper** [comment]
It's not an issue in TeaVM, it's rather an issue in `SpecialArrayList` implementation. Documentation both for `List.add` and `ArrayList.add` says nothing about whether `add(E)` should be or should not be implemented by calling `add(int,E)`. However, I'll implement `add` the way it does OpenJDK anyway, since this should improve performance.
