### ISSUE TITLE
Bug in dead code elimination algorithm?

### ISSUE THREAD

**Issue by salmonb** [konsoletyper/teavm#311]
I already made a [post](https://groups.google.com/forum/?fromgroups#!topic/teavm/t4KqqbXBuSo) in the forum but here is probably a better place to report issues.

I made a reproducer here: https://github.com/salmonb/teavm-issues

The code runs ok in the JVM and compiles with TeaVM but the output javascript code produces this error:

runtime.js:529 Uncaught ReferenceError: tjs_JsonFactory_createNativeObject is not defined
    at tjpl_MapBasedJsonObject_recreateEmptyNativeObject (MapBasedJsonObject.java:29)
    at tjpl_MapBasedJsonObject__init_1 (MapBasedJsonObject.java:17)
    at tjpl_MapJsonObject__init_1 (MapJsonObject.java:12)
    at tjpl_MapJsonObject__init_ (classes.js:2218)
    at tjs_Json_getFactory (Json.java:56)
    at tjs_Json_createObject (Json.java:15)
    at TeaVMThread.t_Application_main (Application.java:12)
    at TeaVMThread.runner (runtime.js:464)
    at TeaVMThread.run (runtime.js:545)
    at TeaVMThread.start (runtime.js:532)

It might be a bug in the dead code elimination algorithm.

You can build the project with maven, then open web file located at teavm-issues\default-method-issue\target\classes\webroot\default-method-issue\index.html, and see the error in the browser console.

**Comment by konsoletyper** [comment]
Hello, yes, I've seen your post in Google Groups, and I started to fix this issue. My investigation has show that this issue is not caused by DCE. Instead, it's an issue in method resolution in virtual call site. This code was written initially for Java 7, which did not allow to define methods in interface, and the resolution process was simple. With Java 8 enhancements, resolution algorithm becomes much more complicated. Now it's possible to find several implementations from different inheritance paths, then algorithm must pick most special implementation among them. I'm in a process.

And yes, you better post issues here rather than to Google Groups.

**Comment by salmonb** [comment]
Many thanks for looking at this. I'm aware it's a quite complex case with several inheritance paths that moreover include default methods. Good luck.
