### ISSUE TITLE
Preview builds from master?

### ISSUE THREAD

**Issue by comick** [konsoletyper/teavm#340]
Preview builds from bintray are from branch `dev-0.6` which is now 4 months old. Many good features worth experimenting with are missing there. How is that branch managed? Is there any preview build from master? Does it make sense to have preview builds from master?

**Comment by konsoletyper** [comment]
No, I don't think preview builds from master is a good idea. Sorry for not updating preview builds that long. Most of the work in last 4 months was on C backend, which was not announced. Unfortunately, some of WebAssembly features got broken because of refactorings needed for C backend. I'll repair WebAssembly and start making recent preview builds.

**Comment by comick** [comment]
That was fast: https://dl.bintray.com/konsoletyper/teavm/org/teavm/teavm-core/0.6.0-dev-529/
Thanks!
