### ISSUE TITLE
TeaVM & ktor incompatibility?

### ISSUE THREAD

**Issue by teras** [konsoletyper/teavm#345]
Hello again

I think I found an incompatibility issue with TeaVM & [ktor](http://ktor.io/) which is not always manifesting itself. 
I have found a minimum example with this incompatibility which I uploaded to this zip file.

The key point is this: if either "by lazy" is missing, or ktor dependency in the pom file is missing, everything works fine.
If both of them are present, then NullPointerException is thrown when "Building JavaScript file"

The problem is not on runtime, but on compile time when trying to resolve dependencies.

Here is the minimum project: [test.zip](https://github.com/konsoletyper/teavm/files/2106936/test.zip)

PS: I think that a minimum project with all files would be better than copying and pasting text, if I learned a lesson from my previous requests :)

**Comment by konsoletyper** [comment]
I fixes the problem, so now attempt to compile this project causes TeaVM to report errors instead of crashing. Looks like `lazy` function uses reflection under the hood so that it can't be used with TeaVM. Perhaps, it could be dirty hacked by TeaVM (i.e. patching implementation of particular methods of Kotlin stdlib). BTW, for what purpose you are trying to compile ktor to JavaScript?

**Comment by teras** [comment]
Thank you, it was just a matter of fixing a NPE I see.

I am just experimenting with technologies and libraries up to now, to get a grip of the compatibility extend of TeaVM. I've checked various containers and standalone providers, as a bundle with the flavour code. I was expecting (flavour java/javascript code) just to sit there silently when being deployed, and produce valid JavaScript code, for the part that will be displayed on the client.

Up to now I am really thrilled by the possibilities.

So, to come back to your original question, I didn't want of course to mix ktor with TeaVM. But it seems although none of them touch the code of the other (ktor part of the code is completely independent of the teavm code and vice versa), for some strange reason just the presence of one of them makes teavm to break. (!!!)

To be frank, since ktor didn't seem to work out of the box, although I'd love to, for my pet project I tried another (java-oriented, not kotlin-oriented) solution.

**Comment by teras** [comment]
It seems that unfortunately the test case still doesn't work.
Although (again) it doesn't touch any kind of code related to ktor, compilation breaks. 
And it is funny because pure kotlin implementations perfectly work.

**Comment by konsoletyper** [comment]
Compiler does not crash anymore, it provides clear explanation what's wrong, so it resolved this particular issue. However, this is not what you want, since you are going to get working result, not compile-time error. And it looked very strange to me that just including ktor as a compile time dependency implies this error. This is how TeaVM basically works: it won't even touch JAR file if there aren't references, direct or indirect, to a class file in this JAR.

I dug a little deeper and found the reason. Reflection prevents many whole-program optimizations performed by TeaVM, that's why I usually avoid it and encourage people to avoid reflection with TeaVM. For number of reasons some users asked me to optimize case like `Class.forName("ClassName")` to just `ClassName.class`. Ok, but that's how Kotlin reflection works: its lightweight part tries to find reflection provider in classpath, and if none found, uses very simple approximation to reflection with limited features, otherwise it delegates calls to provider. To find provider, Kotlin uses `Class.forName()` (as found [here](https://github.com/JetBrains/kotlin/blob/1.2.50/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/Reflection.java#L22)). The optimization I mentioned only works when class denoted by a class literal presents in the compile-time classpath. ktor uses full reflection and causes this optimization to work and to make full reflection reachable by TeaVM. I worked arounded this by prohibiting the optimization for `kotlin.reflect.jvm.internal.ReflectionFactoryImpl`.
