### ISSUE TITLE
can springboot use it direactly?

### ISSUE THREAD

**Issue by baby7305** [konsoletyper/teavm#353]
i have tried it in idea，it runs like springMVC。usually I use springboot and even jhipster，may it be successful?
![image](https://user-images.githubusercontent.com/25588905/44350818-e676d600-a465-11e8-8968-efe3f8258cc6.png)
![image](https://user-images.githubusercontent.com/25588905/44350859-00181d80-a466-11e8-9004-d398ea5ae884.png)

![image](https://user-images.githubusercontent.com/25588905/44351355-5043af80-a467-11e8-8779-79216a9ffb33.png)

**Comment by konsoletyper** [comment]
Sorry, I don't understand the provided description. Can you clarify, i.e. provide details like these:

1. What are you trying to do?
2. What is the expected behaviour of TeaVM?
3. What is the actual behaviour?

Also, TeaVM is not related to Spring Boot, since Spring Boot is the server-side technology, while TeaVM does not work on the server. TeaVM merely generates JS file which can be served statically from any server.

**Comment by baby7305** [comment]
oh。。。。。。I understand，I can separate frontend and backend、client side and server side by restful api。first,I put springboot in tomcat ,then I put teavm in tomcat.thank you!
