### ISSUE TITLE
Is it possible to emit generated code that is not obfuscated and reproduces the API of a Java class?

### ISSUE THREAD

**Issue by kyr0** [konsoletyper/teavm#355]
Hi TeamVM folks :)

could I write a library in Java, like a simple class like: 

    namespace com.acme;

    class FooBar {
        public String whatEver() {
           return "FooBar";
        }
    }

...then compile it into Java bytecode and use TeaVM to generate the JS impl. and put it in some output directory (constructing the inner directory tree just by following the namespace) like:  `$output/com/acme/FooBar.js`. The file `FooBar.js` would come with a `module.exports = Foobar;` call at last line so that I could import this original Java impl. in any JavaScript project and just do:

    import { FooBar} from '$output/com/acme/FooBar';

    new FooBar().whatever(); // "FooBar"

@konsoletyper If this is not possible yet, how hard would it be to implement? And could you please help me to find the right places in the TeaVM code so that I would have a chance to implement it and PR it for you?

Would be awesome!

Thanks and best,
Aron

**Comment by konsoletyper** [comment]
This is nearly impossible to implement. Java was not designed to be compiled to JavaScript, so any attempt to do it in a straight and simple way would end up with large mess of slow JavaScript code. Thus tools like GWT or TeaVM perform a lot of whole program optimizations. This approach requires compilation of a whole application, not module-to-module or class-to-class. The only option provided by TeaVM is to compile bunch of jar files into single highly optimized JavaScript.

To disable obfuscation, say, for debugging reasons, you may play with Maven options (set `minifying` to `false`). However, the generated code would not be intended for calling directly from JavaScript.

If you want to interoperate between Java and JavaScript, you can use [JSO](http://teavm.org/docs/runtime/jso.html) library. In this case TeaVM will generate unobfuscated methods where you ask to. However, this library was not designed to write Java code invokable from JavaScript. Indeed, it can be extended to support this use case. As for now, you can use following workaround. Say, you want `Foo` namespace to provide `bar` method. Here's the code:

```Java
public static void main(String[] args) {
    exportFoo(new Foo() {
        @Override
        public void bar() {
            System.out.println("Bar method works");
        }
    });
}

@JSBody(params = "foo", script = "Foo = foo;")
static native void exportFoo(Foo foo);

interface Foo extends JSObject {
    void bar();
}
```

Anyway, this approach is still incomplete due to following reasons:

1. TeaVM can't generate code in wrapper functions, so you end up with polluted global object. This can be easily improved.
2. This approach requires your JavaScript code to call `main()` function before using `Foo.bar()`.
3. It can't be integrated in CommonJS module system.

The whole JSO implementation is available [here](https://github.com/konsoletyper/teavm/tree/master/jso/impl/src/main/java/org/teavm/jso/impl). This library uses compiler magic to generate interop code.

Please, *do not* to write any PR before you discuss things with me. There's a great chance that I deny the whole PR, since I already have some thoughts about implementing this part of interop, and know lot of corner cases and pitfalls. The best thing you can start with is to describe your use case.

**Comment by kyr0** [comment]
Hi Alexey,

thank you for answering me in full length! I see that my use case is far away from the original goals of this project. As you pointed it out, it's hard to do this, also because the bytecode may lack symbol info like parameter names etc. pp.

My intentional use case is to somehow "transpile" Java libraries (including the whole JDK foundation classes) so I can use them natively in TypeScript. I know GWT because I've built a large web application using GWT 1.8 - but it's a fairly complex framework and I was looking for another option. 

Well, I followed your suggestion that my idea would be almost impossible to implement (using bytecode as the only source of information) -- so I thought... what if someone wrote a Java parser/lexer, creates an AST and transpiles it to TypeScript (without a guarantee that it will work flawlessy for a whole app) -- and it turns out, someone did:

    https://github.com/cincheo/jsweet

This looks like the way to go for me. Anyway, thank you a lot for your time and thoughts!

Best,
Aron

**Comment by kyr0** [comment]
Finally, they even did lots of this work to port the Java Runtime already:

    https://github.com/j4ts/j4ts

**Comment by kyr0** [comment]
Hi @comick ,

yeah cool, this seems to work well too. The only two issues I see are that it:
- requires the whole (big) runtime to work at runtime ;)
- you need to touch/annotate the original library code in order to tell what and how to export

So what I'm after is more like "Export me math.$whatever" as JS code and reproduce the API 1:1 in JS -- best case would be without touching the Java code or having to include a huge runtime.

As a solution, I tried JSweet in the meantime... and it seems to work. There is also some kind of "runtime" involved, but it's only because of their laziness. They pack everything together... with a little more work I see the possibility to generate the TypeScript in a way that it comes with IoC, meaning that one class library is exported atomically but knows about it's dependencies (via generated imports (TS has imports!)) -- that way it would be possible to really export the whole Java runtime + all libs building on top of them (e.g. Apache Commons etc.) to TypeScript. 

Further more, there is the chance to compile this code using AssemblyScript -- AssemblyScript generates WebAssembly code out of TypeScript code. I will also investigate the java.math API impl. of JSweet regarding bignumber.js for the arithmetics.

I'm sure that way it will be possible to come very close to a 100% Java runtime mirror in TypeScript and the JavaScript world. Combined with AssemblyScript, I'm very curious about the performance benchmarks...

**Comment by konsoletyper** [comment]
> requires the whole (big) runtime to work at runtime ;)

Did you measure its size?

As for JSweet. Does it follow 100% Java semantics. As far as I know it does not. Also, what about generated code size when using Java class library (java.util, java.io, etc)? What about performance?

**Comment by rufenerc** [comment]
@comick 
Hello
You suggested:
(function() {
// runtime
// you compiled code
// make main function available in global scope
main()
})()

I tried to follow your  procedure but I failed to do it right. Must be something about namespace. Would you mind to show me your working solution.
Thanks
