### ISSUE TITLE
html:bidir-value update on input only triggered when hitting return

### ISSUE THREAD

**Issue by mojo2012** [konsoletyper/teavm#376]
I wanted to bind a value of an `input` to a field in my view. First I though this should work:
```html
<input type="search" class="top-searchbox" placeholder="Search ..." html:bidir-value="searchInput">
```
But the value is only updated when I hit "return" (same as the real html change event).

I solved this using this html:
```html
<input type="search" class="top-searchbox" placeholder="Search ..." html:value="searchInput" event:keyup="onKeyUpSearchInput(it)">
```

Together with this java code:
```java
public void onKeyUpSearchInput(KeyboardEvent e) {
	this.searchInput = ((HTMLInputElement) e.getTarget()).getValue();
}
```

But it would be nice if the html:change or the html:bidir-value would do exactly that -> update the value on change not just after hitting return.

**Comment by ScraM-Team** [comment]
I agree, it would be useful to have extra events like this that fire as the component is edited, not just when it is committed via enter or loss of focus.  I think @konsoletyper likes for the core bindings to be fairly true to the underlying DOM/browser APIs.  Maybe we could add extra html:bidir-value-live for this real-time style of binding?

P.S. Since this is related to the Flavour framework, you could file it in the flavour issue tracker here: https://github.com/konsoletyper/teavm-flavour/issues
