### ISSUE TITLE
"XXX is not a function" - dead code elemination issue?

### ISSUE THREAD

**Issue by Namek** [konsoletyper/teavm#409]
### Prolog

I have forked the [teavm-libgdx](https://github.com/Namek/teavm-libgdx) project and updated TeaVM + libgdx. The Invaders demo works but I have problem with Super Jumper demo.

### Issue

Many methods simply disappear from the `Matrix4` class in output code. This results in error:
```cbgm_Matrix4_tmpMat.$setToTranslation is not a function```
Indeed, `cbgm_Matrix4_tmpMat` has only few methods:

- idt
- mul
- set
- setToLookAt
- setToOrtho
- setToOrtho2D
- ctor

Here's a screenshots presenting both the exception and list of methods:

![image](https://user-images.githubusercontent.com/31058/62563202-cc0a5800-b882-11e9-84d4-030174b4aad1.png)

There is [Matrix4Emulator class](https://github.com/Namek/teavm-libgdx/blob/master---repro_issues/core/src/main/java/org/teavm/libgdx/emu/Matrix4Emulator.java) which is supposed to replace whole original `Matrix4` class from libgdx.

The replacing code is a bit different from original but I've println-ed all removals and adds of methods/fields, all logs are OK.

The `replaceClass()` method:
https://github.com/Namek/teavm-libgdx/blob/master---repro_issues/core/src/main/java/org/teavm/libgdx/plugin/OverlayTransformer.java#L83-L109

Important bits:

```java
    public OverlayTransformer(){
        Reflections reflections = new Reflections("org.teavm.libgdx.emu");

        Set<Class<?>> annotated = reflections.getTypesAnnotatedWith(Emulate.class);
        for(Class<?> type : annotated){
            Emulate em = type.getAnnotation(Emulate.class);
            Class<?> toEmulate = em.value();
            emulations.put(toEmulate.getTypeName(), type);
        }

        annotated = reflections.getTypesAnnotatedWith(Replace.class);
        for(Class<?> type : annotated){
            Replace em = type.getAnnotation(Replace.class);
            Class<?> toEmulate = em.value();
            replacements.put(toEmulate.getTypeName(), type);
        }
    }

    private void replaceClass(final ClassHolder cls, final ClassReader emuCls) {
        ClassRefsRenamer renamer = new ClassRefsRenamer(referenceCache, preimage ->
                preimage.equals(emuCls.getName()) ? cls.getName() : preimage);
        for (FieldHolder field : cls.getFields().toArray(new FieldHolder[0])) {
            cls.removeField(field);
        }
        for (MethodHolder method : cls.getMethods().toArray(new MethodHolder[0])) {
            cls.removeMethod(method);
        }
        for (FieldReader field : emuCls.getFields()) {
            cls.addField(ModelUtils.copyField(field));
        }
        for (MethodReader method : emuCls.getMethods()) {
            cls.addMethod(renamer.rename(ModelUtils.copyMethod(method)));
        }
    }
```

### Discussion

If that's dead code elemination then it definitely is wrong about the `setToTranslation` method because it's used in the same class, in the method `setToLookAt` (visible on screenshot).

What can I do about it? If that's DCE, as a workaround, can I enforce not deleting methods?

**Comment by trevordilley** [comment]
Curious if it's in need of a ReflectionSupplier?
http://teavm.org/docs/runtime/java-classes.html

**Comment by konsoletyper** [comment]
This can't be worked around. Is there way to reproduce the issue? Also, please check that all replacements fully match in signatures to original methods.

Also, as for libgdx. I abandoned it since I came to conclusion that maintaining these dirty hacks with replacement is a nightmare. Instead, libgdx should be redesigned and refactored to stop using hacks like supersources and stop using reflection. This is only possible if TeaVM-specific code gets incorporated into libgdx codebase and support for TeaVM is integrated deeply into libgdx. So instead of trying to maintain abandoned libgdx backend, try to talk with libgdx contributors and convince them to work on TeaVM backend.

**Comment by konsoletyper** [comment]
The issue might be not with DCE, but with OverlayTransformer. See this code:

```java
for (FieldReader field : emuCls.getFields()) {
            if (cls.getName().contains("Matrix4"))
                System.out.println("  field add " + field.getName());

            cls.addField(ModelUtils.copyField(field));
        }
```

It just copies field without updating its type. It type is declared as Matrix4Emulator, while it should become Matrix4. This cases `Matrix4Emulator` type on callsite inside `<clinit>` method, therefore DCE treats it as a call to `Matrix4Emulator.setToTranslation`, not `Matrix4.setToTranslation`.

**Comment by Namek** [comment]
> Is there way to reproduce the issue?

Oops, sorry, forgot to link that!

### Reproduction

1. Get the source from https://github.com/Namek/teavm-libgdx/tree/master---repro_issues
2. build with `mvn package`
3. See that file `demos\superjumper\webapp\target\teavm-libgdx-superjumper-webapp-0.1.0-SNAPSHOT\teavm\classes.js` does not contain definition of `setToTranslation` method. *However* this method is called, which can be seen in the file:

```
function cbgm_Matrix4_setToLookAt0($this, $position, $target, $up) {
    cbgm_Matrix4_tmpVec.$set1($target).$sub($position);
    $this.$setToLookAt0(cbgm_Matrix4_tmpVec, $up);
    $this.$mul0(cbgm_Matrix4_tmpMat.$setToTranslation( -$position.$x,  -$position.$y,  -$position.$z1));
    return $this;
}
```

### OverlayTransformer

> It just copies field without updating its type.

I don't know how exactly should I update the type. Do you have any example on doing this properly?

 I'll probably workaround this specific class by making it back as it was before (just patching the most basic methods for calculation), however __is it possible to properly replace whole class with another code__?

**Comment by konsoletyper** [comment]
As for OverlayTransformer. You need to replace this line:

```java
cls.addField(ModelUtils.copyField(field));
```

with this one

```java
cls.addField(renamer.rename(field));
```

As for replacing a class. Currently, there's no way to do that. OverlayTransformer is the TeaVM plugin to do that, but nothing like this in TeaVM internally.

**Comment by Namek** [comment]
### OverlayTransformer
Just found out myself the lacking `renamer`. I ended up with:
```java
cls.addField(renamer.rename(ModelUtils.copyField(field)));
```

That worked. Thanks!

### Is it bug?

I don't really understand the exact path of DCE removing this method while still linking to it. Just to make sure before closing the issue, is it a bug of TeaVM or it is not?

**Comment by konsoletyper** [comment]
It's not a bug of TeaVM, it's expected behaviour. Somewhere after 0.5.x I added a bit more restrictive behaviour: when type gets into field, it's filtered against field type. This was performance optimization of DCE. Unfortunately, this broken some code, which has bugs, but which worked fine with 0.5.x. And OverlayTransformer is the code that contained bug. The behaviour was following. Consider you have code:

```java
static final Matrix4Emulator tmpMat = new Matrix4Emulator();
```

this code is turned into field declaration

```java
static final Matrix4Emulator tmpMat;
```

and `<clinit>` method (which is created by Java compiler internally for all class initializers):

```java
static <clinit>() {
    tmpMat = new Matrix4Emulator();
}
```

After processing with OverlayTransformer you get following code:

```java
    tmpMat = new Matrix4();
```

however, `tmpMat` is still Matrix4Emulator. When DCE calculates the set of possible *real* types of `tmpMat`, it processes this line and matches real type (Matrix4) against declared type (Matrix4Emulator), and since these types are different (and Matrix4Emulator is not a supertype for Matrix4), DCE filters out this type. DCE ends up with *empty* set of types of `tmpMat`, which means that any virtual call to any method on `tmpMat` has not effect and does not include any method into reachable set.
