### ISSUE TITLE
Bug or lack of documentation

### ISSUE THREAD

**Issue by verhas** [konsoletyper/teavm#476]
I tried to compile the sample demo application with

```
<targetType>WEBASSEMBLY</targetType>
```

added to the plugin configuration and what I see is

```
Method org.teavm.jso.browser.Window.current()Lorg/teavm/jso/browser/Window; is native but has no org.teavm.interop.Import annotation on it
```

This is version 0.6.1 of TeaVM. I could not find any explanation for this. This is either a bug or some lack of documentation. The most comprehensive explanation I found was http://blog.dmitryalexandrov.net/webassembly-for-java-developers/  but it did not help.

**Comment by konsoletyper** [comment]
JSO is not meant to work with WebAssembly, since it was designed for interaction from JavaScript with JavaScript. WebAssembly is not as seamless in possibilities of interaction. Personally I advice to use JavaScript backend, since WebAssembly does not have any advantages over JavaScript for executing Java. If you still want to play with WebAssembly for some reason, there's no documentation at all. You can look at the [example](https://github.com/konsoletyper/teavm/blob/master/samples/benchmark/src/main/java/org/teavm/samples/benchmark/teavm/WasmBenchmarkStarter.java). Also you should build latest TeaVM yourself, don't use 0.6.1 for WebAssembly, it has bugs in GC.

**Comment by verhas** [comment]
Thanks. It explains.

**Comment by hohwille** [comment]
Issue can IMHO be closed.
