### ISSUE TITLE
entry points causing virtual method invocation

### ISSUE THREAD

**Issue by wh0** [konsoletyper/teavm#57]
When entry points cause virtual method invocation, the dependency checker has no way to know which implementations it needs for those methods. Here's an example.

a base class:
```java
public abstract class Answerer {

	public abstract int getAnswer();

	public static int ask(Answerer impl) {
		return impl.getAnswer();
	}

}
```

a derived class:
```java
public class AnswerImpl extends Answerer {

	@Override
	public int getAnswer() {
		return 5;
	}

	public static Answerer createInstance() {
		return new AnswerImpl();
	}

}
```

Suppose you set `Answerer.ask` and `AnswererImpl.createInstance` as entry points. At no point in Java code does any object actually become the receiver of a `getAnswer` call, so there will be no implementation compiled.

**Comment by konsoletyper** [comment]
When you deal with complicated entry points, you should take it into account. TeaVM can't guess you intentions rearding to what exact implementation you are going to pass to entry point. However, if you declare `main` method as an entry point and write

```java
Answerer.test(new AnswerImpl());
```

TeaVM has enough information to resolve dependencies itself.

Look carefully at `methodAliases` element in [maven plugin description](https://github.com/konsoletyper/teavm/wiki/Building-JavaScript-with-Maven-and-TeaVM). Perhaps you are trying to expose Java library as a JavaScript library? I think, TeaVM needs more convenient tools for this purpose. I presume, JSO can serve this. However, current version of JSO has some problems with dependency resolution as well. This problem is already solved (https://github.com/konsoletyper/teavm/commit/b69b5b92196e940c84a4be230947492c0fcf45bf) and soon will be available in main branch.

**Comment by wh0** [comment]
Thanks, I was just using the `TeaVM.entryPoint` method, so I didn't see that information about how method aliases need type info.
