### ISSUE TITLE
Class not found: java.security.KeyFactory and javax.crypto

### ISSUE THREAD

**Issue by ange-black69** [konsoletyper/teavm#576]
Hello TeaVM team!
I'm trying to build a libgdx application with this [awesome project](https://github.com/xpenatan/gdx-html5-tools).
However, My game are using javax.* package for Diffie-Hellman Key Exchange (I need encryption).
So does TeaVM support Javax security package, or do I need to found a workaround ?

Because at the beggining of the compiling state I got : 
[pastebin](https://pastebin.com/paUKHbe5)

Thank you for your help :)

**Comment by ScraM-Team** [comment]
TeaVM does not support every class from the Java class library.

However, when compiling your code for the web, you may not need Java classes for encryption, since you can use browser APIs for communication, including over secure HTTPS.

For communicating with your server, please look at the REST APIs in Flavour, they make it very easy: http://teavm.org/docs/flavour/rest-client.html
