### ISSUE TITLE
TeaVM links incorrect class 

### ISSUE THREAD

**Issue by ulugbekna** [konsoletyper/teavm#592]
TeaVM (v 0.7.0-dev-1204) in my project seems to confuse two identically named classes. Here's the compilation error that occurs on any `StringBuilder.append` invocation: 

```
ERROR: Method com.google.common.collect.ImmutableSet.iterator()Lcom/google/common/collect/UnmodifiableIterator; was not found
    at com.google.common.collect.ImmutableSet$CachingAsList.iterator(ImmutableSet.java:338)
    at java.util.AbstractCollection.toString(TAbstractCollection.java:146)
    at java.lang.AbstractStringBuilder.insert(TAbstractStringBuilder.java:508)
    at java.lang.AbstractStringBuilder.append(TAbstractStringBuilder.java:504)
    at java.lang.StringBuilder.append(TStringBuilder.java:114)
    ...
```

`StringBuilder.append` in the example above is called by string concatenation such as `"foo" + "bar"`

**Comment by konsoletyper** [comment]
@ulugbekna please, don't take this "stack trace" into account, it's not a stack trace, but some approximation. There are two options here:

1. You debug TeaVM to find and fix problem yourself
2. You provide me access to the code base you are trying to compile and I'll try to fix the issue.

Indeed, sometimes it's quite hard to track down problems like this, but I don't have any solutions for this issue and don't even this it exists in theory.

**Comment by ulugbekna** [comment]
> it's not a stack trace, but some approximation

oh...

--- 

Let me try debugging this myself first. 

How do you usually approach debugging compilation, e.g., logs, running the compiler in debug mode, etc.? 

Is it possible that something scala-specific is causing the problem? Because I don't observe the problem without scala library that I'm adding

**Comment by ulugbekna** [comment]
But how untrustworthy the stacktrace is? Meaning, if we can't trust this stacktrace, are we sure this is particular method not being found?

**Comment by konsoletyper** [comment]
@ulugbekna 

> But how untrustworthy the stacktrace is? 

I don't know how to answer this question unless you provide me the metrics for 'untrustworthyness'.

> Meaning, if we can't trust this stacktrace, are we sure this is particular method not being found?

Most likely the error TeaVM reports on you project is not related to some issue in your project. There's a great chance of TeaVM being broken and reporting invalid error. But the problem is if error reporter being broken, how can we rely on error it reports to find actual bug? I could tell you if I could reproduce the issue, but I don't have any ideas how to do it.

> How do you usually approach debugging compilation, e.g., logs, running the compiler in debug mode, etc.?

As in any other software it depends on the problem. Sometimes you need to debug from IDE, sometimes collect logs, sometimes invent other methods. For this specific issue I would start from debugging `MissingItemsProcessor.java`. You can find some `diagnostics.error` calls there, which are good places to put breakpoints.

> Is it possible that something scala-specific is causing the problem? Because I don't observe the problem without scala library that I'm adding

Everything is possible.
