### ISSUE TITLE
Using libraries to get external url

### ISSUE THREAD

**Issue by gvlpedro** [konsoletyper/teavm#614]
Hi,

"mvn compile" works fine but when I am trying to generate the 'war' file I get an error.

Is it possible use libraries like 'Jsoup (1.15.3)' to access external URLs? I am trying to use it and it seems is not possible to access external world, just packaging the project it complains:

$ **mvn package**
```
[ERROR] Class java.net.SocketTimeoutException was not found
```

The usage of this library is quite simple, actually it works if I execute the code directly from the IDE in a separate main:

```
 Jsoup.connect("https://en.wikipedia.org/").get()
```

**Comment by konsoletyper** [comment]
I'm not sure it's possible. Why not just using `XMLHttpRequest`?

**Comment by gvlpedro** [comment]
I didn't know this alternative, this can be a solution but there are some negative reasons:

- TeaVm should take advantage Java/Scala/kotlin over Javascript
- From Java we can parallelize threads to download data or create a subroutine to download data each hour.
- TeaVm will be more powerful if it is not a black box, should be nice if we can use libraries to connect other services.

It is my humble opinion. I am very interested on this  :)

**Comment by konsoletyper** [comment]
In JavaScript you can also parallelize downloading, but due to ability to run task asynchronously. In fact, having a thread just to download something is an overkill, since CPU is almost not involved and most of the time such thread will freeze on HLT instruction (or rather, OS won't schedule this thread's execution to any available core). 

From browser it's not possible, even in theory, to open direct connections to sockets. Browser comes with HTTP implementation which is available to a developer, but underlying mechanism is not. So there's no way to make Jsoup work in the browser. You can use XHR, you can write a more convenient wrapper around it, and I see no reason why Jsoup is better than browser's HTTP(s) implementation.

**Comment by gvlpedro** [comment]
ok, I will work on your suggestion, thank you very much

**Comment by ScraM-Team** [comment]
@gvlpedro did you have any luck with XMLHttpRequest?

If you are using TeaVM's Flavour library, you can also make calls to RESTful services: http://teavm.org/docs/flavour/rest-client.html

What kind of app are you building?

**Comment by gvlpedro** [comment]
I am using xmlHttpRequest to get data and then store this data in a <div> then I get data from scala, it is a workarround but it works. It will be useful if I use this restful service to avoid store data in a intermediate tag.
Basically I am trying to do a SQL editor from multiple open data endpoints.
