### ISSUE TITLE
Loom / TeaVM's Async

### ISSUE THREAD

**Issue by s5bug** [konsoletyper/teavm#617]
Is there anything I need to be worried about when starting a project in Java 19 when it comes to Virtual Threads? My knowledge of TeaVM is zero, and Virtual Threads very little, so I'm throwing a question out here to get as much useful information as I can.

**Comment by ScraM-Team** [comment]
I would stick to standard, pre-Loom threads in a TeaVM project for now.  That's widely used and explicitly supported.

TeaVM has good support for standard theads.  And in an application running in a browser, it is unusual  to need a huge number of threads, like what Loom is intended for.  What is your use case?

The Loom site says that it consists of additions to the core Java class libraries in the OpenJDK.  TeaVM currently relies on a fork of Apache Harmony Java class libraries, so the code can't be copied due to license incompatibility.  The Loom code would need a clean-room implementation in TeaVM, or someone would have to experiment with running TeaVM using OpenJDK libraries instead of Apache Harmony.

Good luck, and please let us know how it works out.

**Comment by s5bug** [comment]
Thanks for the answer!

This question of mine was sparked by recalling back to a Scala project that was trying to make System.in work in both a JVM and JS context; ScalaJS doesn't have the automatic blocking→nonblocking transformations that TeaVM does, but I was thinking about if System.in were to be "nonblocking" (due to virtual threads) in the first place...

Nothing super applicable to TeaVM, was just curious 🙇
