### ISSUE TITLE
Questions about using teavm for cross platform libraries

### ISSUE THREAD

**Issue by virajsanghvi** [konsoletyper/teavm#671]
I was looking at teavm to support generating cross platform libraries in Java and JavaScript.

I noticed in a stackoverflow (https://stackoverflow.com/questions/67016039/teavm-and-webassembly-build-errors), you didn't recommend running java in wasm - is that mainly because of garbage collection? Is that still the case?

Also, in terms of teavm's wasm support, is it possible to get a string back from an @Export via js? From trying this, I'm assuming it requires jso support?
```
    @Export(name = "hello")
    public static String hello() {
        return "hello world";
    }
```

Assuming wasm isn't the way to go here, would the JS Backend still make sense for a library? Is there an example that demonstrates exporting a function with a primitive response and making that available to JS (e.g. @Export doesn't seem to work for JS Backend)? The example from https://teavm.org/docs/runtime/jso.html assumes the caller is the client application I believe. (Update: think this is answered by https://github.com/konsoletyper/teavm/issues/537)

Apologies if this has been asked before, I searched through issues and looking through examples but wasn't able to find the answer.

Thanks!

**Comment by konsoletyper** [comment]
> is that mainly because of garbage collection

No, that's not because of GC. I'm a bit tired of explaining this, please look through the issues here or in [Google group](https://groups.google.com/g/teavm) my explanation.

> Is there an example that demonstrates exporting a function with a primitive response and making that available to JS

I'm also a bit tired to explain this, sorry. TeaVM was not designed for porting libraries from Java to JS, however it's not impossible, only not very easy. May be somebody from community explains, or there's existing answers here in the issues or in Google groups.

**Comment by virajsanghvi** [comment]
Thanks, closing
