### ISSUE TITLE
I have a problem build the samples.

### ISSUE THREAD

**Issue by MTyson** [konsoletyper/teavm#677]
I couldn't seem to find a happy path to get a working sample built with a WASM example in a WAR file, but I figured it out in a comment below.

**Comment by konsoletyper** [comment]
Sorry, what were the issues?

**Comment by MTyson** [comment]
Sorry, I was trying to do things from a variety of angles and info sources, everything except just: build the root project and install to local repo, then go to the project I want (pi) and build it to a war (which is what I'm after).
That works fine.  Probably the biggest source of confusion is the homepage describing using the maven archetype to start.  That really sent me down a dark alley :)
BTW, I'm writing an article at InfoWorld that is including TeaVM.  Despite my difficulties I think it's a fascinating project ... what are your hopes and plans for it?

**Comment by konsoletyper** [comment]
I see. Yes, due to recent migration to Gradle looks like I broken Maven archetype. Also, it's a bit old and contains outdated dependencies, so I'll update it. Another way to build samples: get `samples/build.gradle.kts` and change version to `0.8.0`. I'll create readme file with instructions.

**Comment by MTyson** [comment]
Cool, yeah, sorry for the frustrated brain dump at the beginning there.

**Comment by konsoletyper** [comment]
As for my plans. Currently, my employer uses TeaVM on production, so I fix issues related to our product as a part of my job, in addition to many other tasks related to product. However, all remaining issues, documentation, etc, I do during free time. Of course, I would develop TeaVM as my full-time job, but I don't have any experience or talent with doing business, so don't know how to establish company and make TeaVM profitable.

**Comment by MTyson** [comment]
Why is Java so hard to turn into WASM?  Is it garbage collection and reflection?

**Comment by konsoletyper** [comment]
Java is not hard to turn into WASM, however it's hard to turn into Wasm due to multiple reasons.  I'm bit tired to explain this in detail, perhaps one day I'll just take all the explanations and turn them into one article on teavm.org. In brief: it's not hard to write own GC or exception handling. It's hard to implement own GC in Wasm due to lack of access to stack. They made it for so called "security". Despite I proposed the ways to keep secure and allow managed runtimes to walk stack safely, they did not listen to me and said that "having a GC built inside Wasm is a more promising way". 5 years passed since then, and GC is still a draft (which is de-facto supported by the browsers). However, GC in Wasm is also imperfect in many ways and the problem is that it can't be perfect due to many reasons.

Also, Wasm lacks all these many useful things familiar to runtime engineers. For example, there's no page protection, which makes it impossible to efficiently handle NullPointerException.

Currently TeaVM produces Wasm binaries, but they are bloated and inefficient, due to extra code in following locations.

* Method prologue, where shadow stack is initialized
* Method epilogue, where shadow stack is cleaned up
* Call site prologue, where shadow stack is maintained and call ID is saved to shadow stack
* Call site epilogue, where catch ID is analysed
* Field access prologue, where receiver is null-checked
* Field write epilogue, where receiver is saved to remembered set for GC

**Comment by MTyson** [comment]
That is actually super interesting, thanks for taking the time when you're tired.

**Comment by MTyson** [comment]
In looking at the code, everything makes sense, except in wasm.html:
```
function putwchars(address, count) {
          let instance = controller.instance;
          let memory = new Int8Array(instance.exports.memory.buffer);
          let string = "";
            for (let i = 0; i < count; ++i) {
              string += $rt_putStdoutCustom(memory[address++]);
            }
          }
          o.teavm.putwcharsOut = putwchars;
          o.teavm.putwcharsErr = putwchars;
        },
```
It kinda makes sense, but could you explain it or direct me to a doc?

**Comment by konsoletyper** [comment]
There's no doc related to doc, sorry. Wasm support is experimental I right now I can't invest more resources into it, including writing documentation. What's exactly unclear in this code?

**Comment by MTyson** [comment]
Give me a one line description of what that code is doing.  I'll quote you directly.

**Comment by konsoletyper** [comment]
This code loads Wasm module, wraps TeaVM JS runtime around it and replaces runtime functions responsible for producing console output, in order to get output not in dev console, but in the web page.

**Comment by MTyson** [comment]
Here's that article with your quote in it: https://www.infoworld.com/article/3692456/hands-on-with-java-and-wasm.html

**Comment by konsoletyper** [comment]
> To use TeaVM you’ll need a [JDK](https://www.infoworld.com/article/3296360/what-is-the-jdk-introduction-to-the-java-development-kit.html) of Java 8 or higher installed.

It's Java 11

> You’ll need Git installed to clone the TeaVM project

Thus users can conclude that they need to build TeaVM themselves, which is not the case: TeaVM is available at Maven Central. I would instead start with something like normal "Hello, world" app to not rely on any repository OR created a repository with code examples for article.

>  Go to the root directory, and type: `/teavm/gradlew`.

*Or*, which is more common, go to the repository directory (i.e. teavm) and run `./gradlew`

> Once that’s done, you can go to the /teavm/samples/pi directory and type: ../../gradlew war

Or rather, which is more common, go to `/teavm/samples` directory and type `./gradlew :pi:war`

> Once that completes, there will be a /teavm/samples/pi/build/libs/pi.war file that we can deploy to a servlet container.

There's much easier way: type `./gradlew :pi:appRunWar`.
