### ISSUE TITLE
Provide a standalone and ready to use distribution like CheerpJ

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [konsoletyper/teavm#692]
I only want to be able to run my favorite Java based applications on the browser as effortless as possible. I don't want to build teavm from source myself. An installer that included everything and ready to use like CheerpJ is greatly appreciated!

https://leaningtech.com/download-cheerpj/

**Comment by konsoletyper** [comment]
TeaVM is available as Maven and Gradle plugins in Maven central and in TeaVM repository, see [documentation](https://teavm.org/docs/intro/getting-started.html). Since in most cases developers use build systems, I found it needless to distribute TeaVM as a CLI tool. If you need another build tool, you can use TeaVM as API, rather that as CLI. There's no documentation available for this API, but it should be self-descriptive, see [TeaVMTool](https://github.com/konsoletyper/teavm/blob/25890adcf8c48f7126d8e828f4f3370b3d93801f/tools/core/src/main/java/org/teavm/tooling/TeaVMTool.java) code.
