### ISSUE TITLE
Usage of Avro with TeaVM

### ISSUE THREAD

**Issue by pabloem** [konsoletyper/teavm#697]
I am trying to use the Avro library (i.e. `org.apache.avro:avro:1.9.0`) in a TeaVM application. In general, the application is new, and does very little, but it does need the Avro library.

So far, I am encountering errors when I try to create an object that belongs to the Avro library. I am not sure how to figure out if the whole library is unsupported / or maybe I'm importing it in a way that is not passing it to TeaVM as it should.

Do you know of people using Avro? How can I figure out if TeaVM has access to the library / whether the library can't be supported, etc?

**Comment by Ihromant** [comment]
Hi Pablo.
You raised an interesting topic about data serialization-deserialization. As I understand, you would like to have transport/storage protocol supported in teavm together with Java backend.
Currently there is no "official" serialization-deserialization approach. There is https://github.com/konsoletyper/teavm-flavour library which I used in the very beginning, but it's JSON-to-Java serialization approach which clones part of Jackson functionality. I used it, was very unhappy and in the end wrote my own JSON-to-Java converter (included record support as well) https://github.com/Ihromant/hexagon/commits/test4 . It's not a maven package/library, I am reusing this code in my closed github repository in transport layer. But this could give you idea about limitations of teavm:
1. There is no reflection.
2. There is no native calls.
Due to this fact, to have your own library which repeats functionality of protobuf/avro/other binary protocols, you need to write your own implementation using teavm metaprogramming https://teavm.org/docs/runtime/metaprogramming.html .
I tried once to use protobuf in teavm, it failed on Java Unsafe usage which is not (and will bever be) implemented in teavm. Jackson fails due to lack of reflection etc.
So, here is explanation why you wouldn't be able to reuse out of the box any of library like avro.
Still, if you will be able to implement some binary protocol/library using TeaVM metaprogramming - it would be great. My data models in some cases have size of around 5 MB and in the future I suppose that I'll switch from JSON-to-Java conversion to binary-to-Java conversion and I would be glad if until that time some binary protocol will be reimplemented in teavm.

Regards,
Ivan

**Comment by siepkes** [comment]
I know it's not what you are asking but it might be of help; The [Square Protobuf implementation](https://github.com/square/wire) does not use reflection and can be used with TeaVM. It's not Avro but it is similar.
