### ISSUE TITLE
Implement JavaScript export mechanism

### ISSUE THREAD

**Issue by konsoletyper** [konsoletyper/teavm#785]
Currently, to export Java objects to JavaScript, developer needs to declare export interface, extending `JSObject`. This is not quite comfortable in many real-world cases, so another, annotation-based mechanism required for brief export.

**Comment by taylortails** [comment]
In 0.9.2, I have just completed a prototype using teavm to compile a java domain model into javascript. I managed to write basic code gen to produce the JSObject interfaces and wrapper classes. I felt the missing pieces that would have helped (which I've implemented locally), are java collection wrappers for List, Set and Map that delegate to JSArray, JSMap and the missing JSSet. It could be that all these wrappers are going to give me performance issues but I'm at least in a place now that in javascript it looks like javascript collections and in java it looks like java collections.

**Comment by konsoletyper** [comment]
@taylortails Good point. Prior I'd say it does not make sense to implement something like this, *at least on TeaVM side*, but now when weakrefs became available in JS and TeaVM utilizes them to generate wrappers for *some* of JS objects, it's also possible to use same mechanist to generate `List` wrappers for `JSArray` and so on. The only thing that it's not fully related to this issue, because this issue about *exporting* Java declarations for JavaScript, while you are talking about *importing* JS delcarations into Java. Please note that exporting Java collections as JS collections is **not possible** (at least, without copying), but it would be possible to at least use JS `Proxy` to expose `List.get` method as JS `list[index]` notation (thou it won't be a real array from JS side)

**Comment by taylortails** [comment]
In my situation I exported the domain model to javascript, for it to be mutated and then passed back (imported), ie. I'm using import and export together.

This was done using JSObject types wrapping java beans (which could be unwrapped when they are later imported again), and also a factory for java Collection types that wrapped native JSObject types (these objects were unwrapped when exporting).

I'm not using weakmaps, I'm just creating JSObject wrappers as they are exported. It's simpler since I don't need object identity (currently). I guess this probably affects performance too but have no numbers.

**Comment by konsoletyper** [comment]
@taylortails you aren't using WeakMaps, but TeaVM *may* use them under the hood.
