### ISSUE TITLE
Can´t split a simple string 

### ISSUE THREAD

**Issue by alan-azvd** [konsoletyper/teavm#82]
When trying to split a string:

```java
public static void main(String[] args) {
        String[] s = new String("1,2").split(",");
    }
````
Maven fails on build.

Using TeaVM version 0.2.1

**Comment by konsoletyper** [comment]
Of course, it fails (but gently, reporting the reason of failure). Look at [supported methods](http://teavm.org/jcl-support/0.2.x/classes/java.lang.String.html). There isn't `split` method. The reason is `split` is actually shorthand for `Pattern.compile(regex).split(this)`. And emulating Java regexps in JavaScript is tough work. Recently, I took regexp engine from old Apache Harmony project. You can build the latest development version of TeaVM yourself and it will do all work, or you can continue with 0.2.1 and avoild `split` method. Please note, that if you choose the first way, you'll get large (about 500 Kb) JavaScript file, since TeaVM must decompile the whole regexp engine for this single invocation.
