### ISSUE TITLE
No teavm IDEA 0.10.0 plugin available

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#927]
Subj.

**Comment by konsoletyper** [comment]
That's because it did not pass verification. JetBrains has suddenly deprecated a class used by plugin. See details here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/19445476369426-Optionally-depending-on-other-plugins-in-2024-1 Can't do anything until I get some response from JetBrains guys
