### ISSUE TITLE
Setting 3D int array to null produces does not set the variable to null

### ISSUE THREAD

**Issue by aloraps** [konsoletyper/teavm#937]
From experience, setting a 3-dimensional integer array to null does not null the variable as intended, leading to unintended consequences/issues. For example, the following code would not print true, and would only set the inner arrays to null.

```
int[][][] exampleArray = null;
if (exampleArray == null)
	System.out.println("True");

```
 
Furthermore, if you tried to get the length of the exampleArray, it would return 4, but if you tried to get the length of any interior arrays ("exampleArray[0].length"), it would throw an error. This caused issues in my own project that are difficult to diagnose, so after spending some time trying to figure out the cause, the 2 images provided compare what works and what threw an error.
 
**Error:** https://imgur.com/ZhFgwsx
 
**Working:** https://imgur.com/vnSomuk

**Comment by konsoletyper** [comment]
Could not reproduce. Listen, if you want bugs to be fixed, you should learn how to properly give a feedback. I remember that it's a case several times: you just leave an issue which I'm unable to reproduce, I write about it and no feedback from your side. I'm not a wizard and without knowing where the problem is I can't guess by some sort of magic, telepathy, etc.

When you posted this piece of code:

```java
int[][][] exampleArray = null;
if (exampleArray == null)
	System.out.println("True");
```

did you try to run it out of your context? Just create a new project, create a class with `public static void main` and paste it? What did you get? I did and got 'True' output. So I presume that the problem is not with assigning `null` to array variable. Perhaps, is has nothing to do with arrays at all. From your screenshot I see that your code is much more complex than these 3 lines of "reproducer" (BTW, **NEVER EVER** do you use screenshots to share some code). I only can presume that if you build your project without optimizations, problem goes.

So what to do? You can try to find out the real case. Try to isolate your problem. Start with isolating your particular method and then try to remove various parts until problem disappears. You can try to build JS without obfuscation and see what code was generated. Anyway, if it's too complex, you can just ask me to do that: just give me your entire code base and provide with full info: how to build your project, which *exact* steps I should perform to reproduce the issue on my side.

**Comment by aloraps** [comment]
Hi,

I apologize for the lack of detail and messiness in the original report. Moving forward, I'll do my best to try to reproduce a simple test case be as detailed as possible when I encounter bugs with TeaVM.

I just spent some more time testing this to really see what's wrong, and what I found was quite peculiar. I tried to produce as many test cases as possible for you. Out of 4 test cases, the first two work, and the last two fail on TeaVM but work fine on Java. Note that the test cases use a boolean that is always set to false.

1. In the first case, I have an if-else statement checking the false boolean like so and then initializing the array. This works fine, and I can access tileArray afterwards:
`        int[][][] tileArray;
        if (!alwaysFalseBoolean)
            tileArray = exampleArray1;
        else
            tileArray = null;
        System.out.println("tileArray[0][0][0]=" + tileArray[0][0][0]);`

3. The 2nd test case is flipped (array setting would be in the else statement), and works fine because if (false) will always be false:
`        int[][][] tileArray2;
        if (false)
            tileArray2 = null;
        else
            tileArray2 = exampleArray2;
        System.out.println("tileArray2[0][0][0]=" + tileArray2[0][0][0]);`


4. The 3rd test case is where things start to get interesting. I have a statement that is equivalent to the 2nd test case, the only difference is that it checks our boolean that is always false... Somehow, this throws an error in TeaVM. I even have a line printing out the value of alwaysFalseBoolean before this if-else statement, which properly prints out "false" as expected, yet this method of assigning the array leads to an exception being thrown.
`        int[][][] tileArray3;
        // Line below prints out false (as intended)
        System.out.println("Value of alwaysFalseBoolean=" + alwaysFalseBoolean);
        if (alwaysFalseBoolean)
            tileArray3 = null;
        else
            tileArray3 = exampleArray3;
        System.out.println("tileArray3[0][0][0]=" + tileArray3[0][0][0]);`


5. The 4th case is similar to the 3rd, except I use ternary to set the array rather than an if-else statement. It produces the same result as the 3rd case though (when using alwaysFalseBoolean as the ternary condition check) and throws an exception. (if I use "false" in the ternary check instead, it works, similar to 3rd case):
`        int[][][] tileArray4 = alwaysFalseBoolean ? null : exampleArray4;
        if (tileArray4 != null)
            System.out.println("Test #4 Passed null-check"); //Works

        if (tileArray4 != null) {
            // Line below causes crash
            System.out.println("tileArray4[0][0][0]=" + tileArray4[0][0][0]);
        }`


So it seems like whatever is causing this has to do with checking a boolean before initializing an array, and somehow that check only works in one order, the "if (!condition) doAction()" but not the other way around. You should be able to easily test it out using the file I attached.

Let me know if you need any other information.

Attached file:
[TeaVMTest.txt](https://github.com/user-attachments/files/16567887/TeaVMTest.txt)



Sample output in browser:

> ===Attempting Test #1 [If-Else setting, 1st order]===
> exampleArray1[0][0][0]=0
> Value of alwaysFalseBoolean=false
> tileArray[0][0][0]=0
> 
> ===Attempting Test #2 [If-Else setting, 2nd order, using 'false' instead of a boolean set to false]===
> exampleArray2[0][0][0]=0
> tileArray2[0][0][0]=0
> 
> /n/n/===Attempting Test #3 [If-Else setting, 2nd order, using alwaysFalseBoolean]===
> exampleArray3[0][0][0]=0
> Value of alwaysFalseBoolean=false
> Uncaught TypeError: Cannot read properties of undefined (reading 'data')
>     at CO (classes.js:51:19)
>     at Eh (classes.js:44:42)
>     at Y.runner (classes.js:3:25)
>     at Y.run (classes.js:35:359)
>     at Y.start (classes.js:35:171)
>     at DY (classes.js:36:253)
>     at classes.js:3:15
>     at basic/:8:5

**Comment by konsoletyper** [comment]
The real cause of issue is following: when we declare multidimensional array variable depending on some condition (this produces _phi_-node), one of branches of which produces `null` literal, and then take first dimension of this array, it's by mistake treated as a JS object and TeaVM (actually, JSO) inserts JS unwrap method.

**Comment by konsoletyper** [comment]
@aloraps can you please build TeaVM locally and test your app against local build?
