### ISSUE TITLE
Calling main() function with arguments splits them up into characters

### ISSUE THREAD

**Issue by stikdragon** [konsoletyper/teavm#959]
My HTML file simply calls `<script>main("admin");</script>`.  This is meant to pass a single string to the `public static void main(String[] args) {..}` method in java-land, but what i actually seem to get is an array of 5 strings with a single character in each:

![image](https://github.com/user-attachments/assets/1cc0dffa-4d01-45dc-9a4d-af9fa6aef040)

**Comment by konsoletyper** [comment]
Hi. Please, try `main(["admin"])`.

**Comment by stikdragon** [comment]
That solves it - is this behaviour intentional?  It's a little unintuitive

**Comment by Ihromant** [comment]
I think that if you want to pass parameters not wrapped into array to your main, you could use
```
public static void main(String... args) {\
// code
}
```
instead. Still, I don't know whether TeaVM properly compiles such entry point.

**Comment by konsoletyper** [comment]
> is this behaviour intentional? It's a little unintuitive

@stikdragon one reason is the ability to pass callback as a second argument. TeaVM can emulate threads and blocking code (like `Thread.sleep`), so from prospective of JS code `main` method does not necessarily return immediately. I know that there would be a better alternative - to return `Promise`, but TeaVM started in the ancient ages when ES6 was not fully there - and when some projects still had to support IE8 or even IE7. This could be reviewed since then, but frankly speaking nobody complained. I event doubt that anyone ever used ability to pass strings to `main` method (or callback as well), except for internal TeaVM tooling, that, for example, runs tests.
