### ISSUE TITLE
Wrong static property values are used

### ISSUE THREAD

**Issue by skerit** [konsoletyper/teavm#972]
I've structured a project like this:

## `server/SpecificBlast.java`:

```java
public class SpecificBlast {
    public final static boolean IS_SERVER = true;
}
```

## `common/Blast.java`:

```java
public class Blast extends SpecificBlast {
    public static void main(String[] args) {
        if (Blast.IS_SERVER) {
            System.out.println("On server");
        } else {
            System.out.println("On browser");
        }
    }
}
```

## `browser/TeaSpecificBlast.java`:

```java
public class TeaSpecificBlast {
    public final static boolean IS_SERVER = false;
}
```

And I configured my `teavm.properties` file like this:

```
mapPackageHierarchy|be.elevenways.protoblast.browser=be.elevenways.protoblast.server
stripPrefixFromPackageHierarchyClasses|be.elevenways.protoblast.browser=Tea
```

But whenever I run the generated JavaScript code, it always puts out **On server** in the console.

When I switch from using static booleans to a static method, like so:

```java
public class SpecificBlast {
    public static boolean isServer() {
        return true;
    }
}

public class Blast extends SpecificBlast {
    public static void main(String[] args) {
        if (Blast.isServer()) {
            System.out.println("On server");
        } else {
            System.out.println("On browser");
        }
    }
}

public class TeaSpecificBlast {
    public static boolean isServer() {
        return false;
    }
}
```

it does work as expected.

**Comment by SquidDev** [comment]
The Java compiler will inline constants from `static final` fields, even across modules. This means that the `Blast.main` is compiled to `if(true)` by `javac`, before TeaVM even sees the classes.

**Comment by skerit** [comment]
Ah yes, that makes sense. And then TeaVM converts the bytecode to JavaScript.

Is there a more robust alternative to the `mapPackageHierarchy` solution? Some kind of gradle plugin?

**Comment by konsoletyper** [comment]
@skerit what do you mean by "more robust"? What's current solution missing in your opinion?

**Comment by skerit** [comment]
I think what I'm after is some kind of pre-processor step, one that happens before the actual bytecode compilation. I'm going to look into the [manifold compiler plugins](https://github.com/manifold-systems/manifold) for that.

**Comment by skerit** [comment]
Alright, that works beautifully.

I modify the compiler arguments like so when generating the JavaScript:

```groovy
tasks.withType(JavaCompile) {
    // If you DO NOT define a module-info.java file:
    options.compilerArgs += ['-Xplugin:Manifold']

    if (gradle.startParameter.taskNames.contains('generateJavaScript')) {
        options.compilerArgs += ['-AIS_TEAVM=true']
    }
}
```

And in my source files I can now use this:

```java
#if IS_TEAVM
import be.elevenways.protoblast.browser.TeaSpecificBlast;
#else
import be.elevenways.protoblast.server.SpecificBlast;
#endif

public class Blast #if IS_TEAVM extends TeaSpecificBlast #else extends SpecificBlast #endif { }
```

The problem I have now is that when using this library (which I published locally) in the main project, it only ever uses the compiled version without the `IS_TEAVM` check. So there, the `Blast.IS_SERVER` will always be true, even when generating the JavaScript files

What would the best way to work around this be?

**Comment by konsoletyper** [comment]
> What would the best way to work around this be?

If you want help, then I need more context. Perhaps, you chosen completely wrong approach. For example, why don't you use just methods instead of `static final` fields? And why are you inheriting from platform-specific classes? Normally, this works completely different: there's an abstract base class that implements common logic and its inheritors that implement platform-specific logic.

If you want users to extent some class that's implemented differently on Web and normal JVM, then alternative approaches can be chosen. For example, this class can itself delegate platform-specific features to some interface that has platform-specific implementations. Like:

```java
public class Blast {
    private BlastStrategy strategy = acquireStrategy();

    // here are methods of Blast class that delegate some platform-specific stuff to BlastStrategy.
}

class WebBlastStrategy implements BlastStrategy {
    // TeaVM-specific implementation
}

class JvmBlastStrategy implements BlastStrategy {
    // JVM-specific implementation
}
```

now you have several options to implement `acquireStrategy`:

1. Use `@PlatformMarker` annotation. Sorry, there's no documentation for this, but you can clone TeaVM sources and search for uses of this annotation, specifically, `PlatformDetector` class. TeaVM uses this approach itself to implement backend-specific stuff in Java class library implementation. Also, don't hesitate to ask me if for details if you choose this approach.
2. Use [ServiceLoader](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html) mechanism. You can have one Jar file for platform-neutral implementation and two Jar files for platform-specific implementations. In this case each own set of declarations in `META-INF/services`.
3. Move `acquireStrategy` to another class (say, `BlastStrategyProvider`). Implement tree modules. One is the stub module, on which you platform-neutral module depends (as as compile-only dependency), which implements `BlastStrategyProvider.acquireStrategy` as a `native` method or simply throws some exception, and two others, which implement the same for each platform.
